/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		Calculator: typeof import('./components/CustomCalculator.vue')['default']
		CustomCalculator: typeof import('./components/CustomCalculator.vue')['default']
		CustomDialog: typeof import('./components/CustomDialog.vue')['default']
		CustomHeader: typeof import('./components/CustomHeader.vue')['default']
		ElButto: typeof import('element-plus/es')['ElButto']
		ElButton: typeof import('element-plus/es')['ElButton']
		ElCard: typeof import('element-plus/es')['ElCard']
		ElCol: typeof import('element-plus/es')['ElCol']
		ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
		ElDialog: typeof import('element-plus/es')['ElDialog']
		ElRow: typeof import('element-plus/es')['ElRow']
		ElText: typeof import('element-plus/es')['ElText']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
	}
}
