/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		CustomCalculator: typeof import('./components/CustomCalculator.vue')['default']
		CustomDialog: typeof import('./components/CustomDialog.vue')['default']
		CustomerService: typeof import('./components/CustomerService.vue')['default']
		CustomFooter: typeof import('./components/CustomFooter.vue')['default']
		CustomHeader: typeof import('./components/CustomHeader.vue')['default']
		DeviceDetect: typeof import('./components/DeviceDetect.vue')['default']
		ElAvatar: typeof import('element-plus/es')['ElAvatar']
		ElButton: typeof import('element-plus/es')['ElButton']
		ElCard: typeof import('element-plus/es')['ElCard']
		ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
		ElCol: typeof import('element-plus/es')['ElCol']
		ElDialog: typeof import('element-plus/es')['ElDialog']
		ElForm: typeof import('element-plus/es')['ElForm']
		ElFormItem: typeof import('element-plus/es')['ElFormItem']
		ElIcon: typeof import('element-plus/es')['ElIcon']
		ElInput: typeof import('element-plus/es')['ElInput']
		ElProgress: typeof import('element-plus/es')['ElProgress']
		ElRow: typeof import('element-plus/es')['ElRow']
		ElStep: typeof import('element-plus/es')['ElStep']
		ElSteps: typeof import('element-plus/es')['ElSteps']
		ElText: typeof import('element-plus/es')['ElText']
		NoFixedDialog: typeof import('./components/NoFixedDialog.vue')['default']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
	}
}
