/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		Calculator: typeof import('./components/CustomCalculator.vue')['default']
		CustomCalculator: typeof import('./components/CustomCalculator.vue')['default']
		CustomDialog: typeof import('./components/CustomDialog.vue')['default']
		Customer: typeof import('./components/CustomerService.vue')['default']
		CustomerService: typeof import('./components/CustomerService.vue')['default']
		CustomFooter: typeof import('./components/CustomFooter.vue')['default']
		CustomHeader: typeof import('./components/CustomHeader.vue')['default']
		DeviceDetect: typeof import('./components/DeviceDetect.vue')['default']
		ElAvatar: typeof import('element-plus/es')['ElAvatar']
		ElButton: typeof import('element-plus/es')['ElButton']
		ElCard: typeof import('element-plus/es')['ElCard']
		ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
		ElCol: typeof import('element-plus/es')['ElCol']
		ElColumn: typeof import('element-plus/es')['ElColumn']
		ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
		ElDialog: typeof import('element-plus/es')['ElDialog']
		ElForm: typeof import('element-plus/es')['ElForm']
		ElFormItem: typeof import('element-plus/es')['ElFormItem']
		ElIcon: typeof import('element-plus/es')['ElIcon']
		ElInput: typeof import('element-plus/es')['ElInput']
		ElRow: typeof import('element-plus/es')['ElRow']
		ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
		ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
		ElSketonItem: typeof import('element-plus/es')['ElSketonItem']
		ElStep: typeof import('element-plus/es')['ElStep']
		ElSteps: typeof import('element-plus/es')['ElSteps']
		ElSwitch: typeof import('element-plus/es')['ElSwitch']
		ElText: typeof import('element-plus/es')['ElText']
		NoFixedDialog: typeof import('./components/NoFixedDialog.vue')['default']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
	}
}
